### ISSUE TITLE
Dockerize the Stream Registry

### ISSUE THREAD

**Issue by phirsave** [homeaway/stream-registry#1]
Desired Behavior
==============================
First time users especially if they are developers who want to play with this offering would find it useful to have a Dockerized install available to them. Provide some sample data, topology and prod/consumers out of the box so there is a script to follow. Make this script become available in the documentation.

Benefits
==============================

* Make installation and on-boarding easier
* A simple working example out of the box to help educate and get value
* Documentation of key customer journey touch points

**Comment by neoword** [comment]
also.. (probably a separate issue) need to provide examples for the developer journey.

See https://github.com/confluentinc/examples/blob/5.0.1-post/postgres-debezium-ksql-elasticsearch/postgres-debezium-ksql-elasticsearch-docker-short.adoc

**Comment by cricket007** [comment]
I commented on this internally, but this seems to be a useful way to solve the issue. 
https://github.com/GoogleContainerTools/jib

**Comment by neoword** [comment]
Make sure we address #9

**Comment by nathanwalther** [comment]
> also.. (probably a separate issue) need to provide examples for the developer journey.

I agree with it as a separate issue. Let's move this to issue #9, out of scope here.

**Comment by cricket007** [comment]
See https://github.com/GoogleContainerTools/jib/pull/1290 for inspiration
