### ISSUE TITLE
Stream with same Schema registered mutiple times (count > 100) throws Error

### ISSUE THREAD

**Issue by prabhakar1983** [homeaway/stream-registry#100]
# Expected Behavior

Streams with same schema registered multiple times should not throw error.

# Actual Behavior

When you update a Stream with the same Schema multiple times, it throws an error
```
java.lang.IllegalStateException: Too many schema objects created for ${subject name}
```

# Steps to Reproduce

Option 1: Register a Stream with same Schema for 100 times. When we created the SchemaRegistryClient, we had set the initialCapacity to 100. 
Our Deployment environment healthcheck reflects this behavior.

Option 2:The behavior is simulated in the test case.
https://github.com/prabhakar1983/stream-registry/blob/b82ef92e6b85d7c0569677fea11467fe27cf9c37/core/src/test/java/com/homeaway/streamplatform/streamregistry/extensions/schema/SchemaManagerIT.java#L37

# Additional Information

There is an open issue with confluent on this https://github.com/confluentinc/schema-registry/issues/894
https://github.com/confluentinc/schema-registry/issues/172
Gwen has a PR for this currently open 
https://github.com/confluentinc/schema-registry/pull/827

**Comment by neoword** [comment]
Removing from active development until PR is done.
Will investigate possible workarounds.
