### ISSUE TITLE
Collapse KafkaManager into StreamInfrastructureManager

### ISSUE THREAD

**Issue by neoword** [homeaway/stream-registry#109]
# Desired Behavior

Don't need two interfaces.  Combine KafkaManager behavior into StreamInfrastructureManager.

# Benefits

* Less is more
* StreamInfrastructureManager exists to abstract underlying stream platform

**Comment by scunniff** [comment]
What is StreamInfrastructureManager called now? I can't seem to find it (other than a reference to "StreamInfraManager" in config-dev.yaml and in architecture/index.md). I figure this interface was renamed at some point.

**Comment by neoword** [comment]
https://github.com/homeaway/stream-registry/blob/dcd33a4e2c4b2de1b3c202d3447c30fb5d959972/core/src/main/java/com/homeaway/streamplatform/streamregistry/db/dao/KafkaManager.java

and

https://github.com/homeaway/stream-registry/blob/dcd33a4e2c4b2de1b3c202d3447c30fb5d959972/infra-provider/src/main/java/com/homeaway/streamplatform/streamregistry/provider/InfraManager.java

**Comment by neoword** [comment]
Realize that this is not straightforward... the idea being that `InfraManager` should abstract out the stream infrastructure, and anything specific to Kafka should be up to the implementation of that `InfraManager`.
