### ISSUE TITLE
Add OpenAPI spec 

### ISSUE THREAD

**Issue by cricket007** [homeaway/stream-registry#11]
Copy the one we have, or reimplement it, if needed.

Maybe useful - https://niftysoft.github.io/devlog/2018/05/03/open-api-v3.html

**Comment by neoword** [comment]
Yeah. However, I think I would like to explore GraphQL as a swagger replacement soon.

**Comment by neoword** [comment]
Will likely not do in favor of #38.
Marking won't do for now.

**Comment by cricket007** [comment]
GraphQL doesn't handle HTTP errors. How do you accomodate for that?

**Comment by neoword** [comment]
re: GraphQL errors
- Addressed elsewhere... (e.g. https://www.apollographql.com/docs/react/features/error-handling.html)

Also... not saying only GraphQL... might switch to GRPC or something more friendly than swagger/OpenAPI.
