### ISSUE TITLE
Update Stream registry Schema to enable composable platform architecture

### ISSUE THREAD

**Issue by vinayakponangi** [homeaway/stream-registry#12]
Desired Behavior
==============================

Please describe the new behavior stream-registry project should have.

Benefits
==============================

Please list the benefits of updating the stream-registry project 
to have the new behavior. E.g.:

* Builds more quickly
* Enable compatibility with a new platform

**Comment by neoword** [comment]
@vinayakponangi can you be more specific in the description on this one?
Otherwise please consider closing.

**Comment by neoword** [comment]
Speaking with @vinayakponangi #41 closes this.
