### ISSUE TITLE
Update swagger definitions to align with the North start architecture document

### ISSUE THREAD

**Issue by vinayakponangi** [homeaway/stream-registry#13]
Desired Behavior
==============================

Please describe the new behavior stream-registry project should have.

Benefits
==============================

Please list the benefits of updating the stream-registry project 
to have the new behavior. E.g.:

* Builds more quickly
* Enable compatibility with a new platform

**Comment by neoword** [comment]
@vinayakponangi can you specify the details of this issue? This seems like boilerplate. Otherwise close.

**Comment by neoword** [comment]
Won't Do. We will address as features are added.
