### ISSUE TITLE
Track all the log statements of each Http Request using MDC

### ISSUE THREAD

**Issue by prabhakar1983** [homeaway/stream-registry#132]
# Desired Behavior

Track all the log statements of each Http Request using MDC

# Benefits

1. Trace and group all the log statements for a single Http Request , which will help in debugging issues
2. Send back the UUID in the http response headers so that tracking and debugging issues are easier

**Comment by neoword** [comment]
Can you consider adding a facility for a filter and letting folks override the logging mechanism with their own logging template?

Then this way different adopters could specify their own filters.

Not sure that we want to get so opinionated with the public offering.

**Comment by neoword** [comment]
Marking this `won't do` in favor of #135.
