### ISSUE TITLE
Get clusters throws 500

### ISSUE THREAD

**Issue by arunvasudevan** [homeaway/stream-registry#146]
# Expected Behavior

When searching for invalid values in search field it should throw not found 

# Actual Behavior

It throws a 500 error

# Steps to Reproduce

1. Get Clusters
2. Search for "invalid" in the type field.
3. Throws a 500 error.

**Comment by scunniff** [comment]
Should this be closed? Based on Arun's PR (#147) it looks like this was fixed.
