### ISSUE TITLE
package name cleanup

### ISSUE THREAD

**Issue by nathanwalther** [homeaway/stream-registry#16]
Desired Behavior
==============================

Renamed Java packages to reflect that this is the Stream Registry, which is a component of the Streaming Platform

Benefits
==============================

**Comment by cricket007** [comment]
And Avro namespaces

**Comment by nathanwalther** [comment]
I just discussed with @neoword and @vinayakponangi and we decided to split the Avro namespace change into a new issue because it breaks compatibility.
