### ISSUE TITLE
Update README.md to reflect 0.3.x milestone changes

### ISSUE THREAD

**Issue by vinayakponangi** [homeaway/stream-registry#21]
Desired Behavior
==============================

Please describe the new behavior stream-registry project should have.

Benefits
==============================

Please list the benefits of updating the stream-registry project 
to have the new behavior. E.g.:

* Builds more quickly
* Enable compatibility with a new platform

**Comment by cricket007** [comment]
There's a maven changelog plugin, somewhere... Helps the current manual documentation process

**Comment by neoword** [comment]
@vinayakponangi can you update the PR description? I believe this is just the boilerplate. Otherwise, lets close.

**Comment by vinayakponangi** [comment]
I agree this is just boilerplate. Closing it.
