### ISSUE TITLE
Update documentation with architecture diagram to represent composable platform

### ISSUE THREAD

**Issue by vinayakponangi** [homeaway/stream-registry#24]
Desired Behavior
==============================

Imperative/Declarative components should be part of the bigger composable architecture

Please describe the new behavior stream-registry project should have.

Benefits
==============================

Please list the benefits of updating the stream-registry project 
to have the new behavior. E.g.:

* Builds more quickly
* Enable compatibility with a new platform

**Comment by neoword** [comment]
Closing as duplicate of #4
