### ISSUE TITLE
Stream registry Confluent compatibility is documented

### ISSUE THREAD

**Issue by vinayakponangi** [homeaway/stream-registry#25]
Desired Behavior
==============================

Stream registry compatibility to current Confluent/Kafka versions should be clearly documented in the README.

Benefits
==============================

* Developers and Contributors can at-a-glance determine whether or not they can immediately use StreamRegistry

**Comment by cricket007** [comment]
Kafka 0.10.2+, correct?

https://cwiki.apache.org/confluence/display/KAFKA/Compatibility+Matrix

**Comment by neoword** [comment]
@cricket007 I think the idea here was more to point out what clients we envision supporting.
I think we should open source one ore more client libraries soon (starting with Java/Kafka).

@vinayakponangi anything more to add here ?

**Comment by cricket007** [comment]
That's not how I interpret "compatibility to current Confluent/Kafka versions".

Sure, the non-Java clients have their own level of compatibility, but this project, as a Java based HTTP service, shouldn't have issues with Python, JS, etc. versioning as the Kafka connections to Kafka aren't being handled by Stream Registry.

**Comment by vinayakponangi** [comment]
I agree. I think for now the pom captures what the SR compatible version for confluent and Kafka are. So we can close this for now.

**Comment by cricket007** [comment]
At the very least, could say something along the lines of 

> HomeAway started development of the StreamRegistry, starting with Kafka 0.11 / Confluent 3.3.x, and as since upgraded to 1.1, Confluent 4.1.x. As per [compatibility matrix], Stream Registry should be compatibile with Kafka brokers 0.10 and higher.
