### ISSUE TITLE
Missing info on README.md

### ISSUE THREAD

**Issue by eleduardo** [homeaway/stream-registry#3]
Desired Behavior
==============================
README.md should probably have a quick description on what the components are inside the project, ideally also a nice drawing/diagram that explains how the components fit together.

Benefits
==============================
Potential contributors don't need to dive into code to start understanding what they are looking at.

**Comment by neoword** [comment]
Will address in #4

**Comment by neoword** [comment]
Great idea @eleduardo.  We were aware that the documentation needed some work ... will update in #4 as well as other things in the hopper.
