### ISSUE TITLE
Healthcheck endpoint isn't exposed as documented

### ISSUE THREAD

**Issue by nathanwalther** [homeaway/stream-registry#46]
Expected Behavior
==============================

Healthcheck response at `http://localhost:8081/healthcheck`, or corrected documentation with the actual port and path.

Actual Behavior
==============================

Endpoint returns 404 response.

Steps to Reproduce
==============================

1. `make build`
2. `make run`
3. browse to `http://localhost:8081/healthcheck`

Additional Information
==============================

I also checked `http://localhost:8080/healthcheck` (note port difference) just to be sure, also got a 404 response.

**Comment by nathanwalther** [comment]
I left a TODO comment for "(issue #46)" in the code.

**Comment by cricket007** [comment]
It should be `/private/healthcheck`  -- https://github.com/homeaway/stream-registry/blob/master/config-dev.yaml#L4

**Comment by neoword** [comment]
![image](https://user-images.githubusercontent.com/552515/50198780-c4f20200-0312-11e9-9e55-deaa50a55a2c.png)
Works for me... will update TODOs and use that to fix this.
