### ISSUE TITLE
Stream Upsert Ignores `streamName` path param

### ISSUE THREAD

**Issue by westeras** [homeaway/stream-registry#66]
# Desired Behavior

https://github.com/homeaway/stream-registry/blob/080e487c9a763b4d1847fd72ebfe375793ef46e9/core/src/main/java/com/homeaway/streamingplatform/resource/StreamResource.java#L89-L92

The stream resource should validate the provided `streamName` path param against the stream name in the Stream entity.  In addition, currently any feign clients generated against the SR's swagger endpoint behave unpredictably due to literal `"{streamName}"` being left in the URL

# Benefits

* Adds a layer of protection/validation on stream upsert
* Fixes feign client behavior derived from swagger

**Comment by neoword** [comment]
#69 Fixes this.
