### ISSUE TITLE
Module Layout Recommendation

### ISSUE THREAD

**Issue by neoword** [homeaway/stream-registry#84]
# Desired Behavior

#79 and #81 are discussing how to break up core into plugins and implementations.
We need a recommendation on the package layout and subsequent versioning representation.

# Benefits

* Clarity around why we have packaged modules in SR as they ar

**Comment by cricket007** [comment]
Conversation w/ @nathanwalther about SoC

> Nathan Walther [4:51 PM]
> what do you think of simply an `api` module with all the interfaces for validators, infra-providers, etc…, and a second module for `core` or whatever we want to call it that's the private implementation of that api?
> 
> Jordan Moore [4:57 PM]
> So a "monolithic" interface module? I guess that could work. Doesn't really demonstrate the separation of concerns, though
> 
> Nathan Walther [5:15 PM]
> right, because I think the essential part is separating the api (being the contract with users) from the implementation, but I don't think separating the concerns finer than that merits the overhead of so many modules
> 
> Jordan Moore [5:17 PM]
> Even if the Infra Provider doesn't necessarily need a validator and vice versa? (edited) 
> 
> Nathan Walther [5:18 PM]
> yep, acknowledging that tradeoff

I think that the "private implementation" though still warrants pulling out the `core.dao` package and the `core.dao.impl` is that private implementation.

**Comment by cricket007** [comment]
I don't understand the comment about versioning.

**Comment by nathanwalther** [comment]
We should consider if we want the code to have the same version or different as part of deciding among separating by package, module, or repository.

**Comment by nathanwalther** [comment]
For now let's leave the modules as they are. I expect we'll want an `api` module with its own jar artifact but I'd rather wait until the api has settled down and the use cases are clearer. Ideally we'll have 2+ implementations of each interface to illustrate the usage. It's ok for implementors to develop against the `core` module prior to a 1.0 release.

**Comment by cricket007** [comment]
Sorry, what is unclear?

I'll give one example - managing the infrastructure using a Kafka topic is brittle without ACLs. Rather it should be possible to define the infrastructure using a Hashmap or from a static file

**Comment by neoword** [comment]
Agree that when we have the second implementation this will make sense.  Until then, can we defer when we have a concrete second implementation to go with (preferably one that is not made up)?
Until then, lets mark it and move on.
