### ISSUE TITLE
Needs README

### ISSUE THREAD

**Issue by tlivings** [homeaway/stream-registry#9]
Overview and description, how to use, examples, etc.

**Comment by neoword** [comment]
Will get addressed in #1

**Comment by cricket007** [comment]
I feel like this should be reopened?

Docker isn't a requirement for usage documentation

**Comment by nathanwalther** [comment]
Yes, let's reopen this and separate it from #1. The documented developer journey is valuable independently of whether the app is running inside docker or not.

**Comment by neoword** [comment]
Agreed
